apiVersion: apps/v1
kind: Deployment
metadata:
  name: ueransim-gnb
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ueransim-gnb
  template:
    metadata:
      labels:
        app: ueransim-gnb
    spec:
      containers:
      - name: gnb
        image: ueransim:latest
        imagePullPolicy: IfNotPresent
        command:
        - /bin/bash
        - -c
        args:
        - bash /opt/UERANSIM/start-gnb.sh
        volumeMounts:
        - name: ueransim-startup
          mountPath: /opt/UERANSIM/start-gnb.sh
          subPath: start-gnb.sh
      volumes:
      - name: ueransim-startup
        configMap:
          name: ueransim-startup
