apiVersion: apps/v1
kind: Deployment
metadata:
  name: ueransim-ue
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ueransim-ue
  template:
    metadata:
      labels:
        app: ueransim-ue
    spec:
      containers:
      - name: ue
        image: ueransim:latest
        command:
        - /bin/bash
        - -c
        args:
        - bash /opt/UERANSIM/start-ue.sh
        volumeMounts:
        - name: ueransim-startup
          mountPath: /opt/UERANSIM/start-ue.sh
          subPath: start-ue.sh
        - name: ueransim-ue-config
          mountPath: /opt/UERANSIM/config/open5gs-ue.yaml
          subPath: open5gs-ue.yaml
      volumes:
      - name: ueransim-startup
        configMap:
          name: ueransim-startup
      - name: ueransim-ue-config
        configMap:
          name: ueransim-ue-config
