apiVersion: v1
data:
  start-gnb.sh: |
    #!/bin/bash

    IP=$(hostname -i)

    sed -i "s/linkIp:.*/linkIp: ${IP}/" /opt/UERANSIM/config/open5gs-gnb.yaml
    sed -i "s/ngapIp:.*/ngapIp: ${IP}/" /opt/UERANSIM/config/open5gs-gnb.yaml
    sed -i "s/gtpIp:.*/gtpIp: ${IP}/" /opt/UERANSIM/config/open5gs-gnb.yaml
    sed -i "s/address:.*/address: amf/" /opt/UERANSIM/config/open5gs-gnb.yaml

    cd /opt/UERANSIM

    ./build/nr-gnb -c config/open5gs-gnb.yaml
kind: ConfigMap
metadata:
  creationTimestamp: "2026-08-04T09:27:06Z"
  name: ueransim-startup
  namespace: open5gs
  resourceVersion: "40438"
  uid: 2ca7b2ea-cd86-4da4-9ea1-5a9cd3046906
