apiVersion: apps/v1
kind: Deployment
metadata:
  name: amf
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amf
  template:
    metadata:
      labels:
        app: amf
    spec:
      containers:
      - name: amf
        image: gradiant/open5gs:2.7.0
        command: ["/bin/bash", "-c"]
        args:
        - |
          open5gs-amfd
        ports:
        - containerPort: 7777
          protocol: TCP
        - containerPort: 38412
          protocol: SCTP
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: amf
  namespace: open5gs
spec:
  selector:
    app: amf
  ports:
  - name: sbi
    protocol: TCP
    port: 7777
    targetPort: 7777
  - name: ngap
    protocol: SCTP
    port: 38412
    targetPort: 38412
  type: LoadBalancer
