apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcf
  namespace: open5gs

spec:
  replicas: 1

  selector:
    matchLabels:
      app: pcf

  template:
    metadata:
      labels:
        app: pcf

    spec:
      containers:
      - name: pcf

        image: gradiant/open5gs:2.7.0
        imagePullPolicy: IfNotPresent

        env:
        - name: DB_URI
          value: mongodb://mongodb:27017/open5gs

        command:
        - /bin/bash
        - -c

        args:
        - |
          open5gs-pcfd -c /opt/open5gs/etc/open5gs/pcf.yaml

        ports:
        - containerPort: 7777
          protocol: TCP

        volumeMounts:
        - name: pcf-config
          mountPath: /opt/open5gs/etc/open5gs/pcf.yaml
          subPath: pcf.yaml

      volumes:
      - name: pcf-config
        configMap:
          name: pcf-config

---
apiVersion: v1
kind: Service
metadata:
  name: pcf
  namespace: open5gs

spec:
  selector:
    app: pcf

  ports:
  - name: sbi
    port: 7777
    targetPort: 7777
