apiVersion: apps/v1
kind: Deployment
metadata:
  name: smf
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smf
  template:
    metadata:
      labels:
        app: smf
    spec:
      containers:
      - name: smf
        image: gradiant/open5gs:2.7.0
        command: ["/bin/bash", "-c"]
        args:
          - open5gs-smfd
        ports:
        - containerPort: 7777
        volumeMounts:
        - name: smf-config
          mountPath: /opt/open5gs/etc/open5gs/smf.yaml
          subPath: smf.yaml
      volumes:
      - name: smf-config
        configMap:
          name: smf-config
---
apiVersion: v1
kind: Service
metadata:
  name: smf
  namespace: open5gs
spec:
  selector:
    app: smf
  ports:
  - protocol: TCP
    port: 7777
    targetPort: 7777
