apiVersion: v1
kind: ConfigMap
metadata:
  name: upf-config
  namespace: open5gs

data:
  upf.yaml: |
    logger:
      file: /opt/open5gs/var/log/open5gs/upf.log

    upf:

      pfcp:
        server:
          - dev: eth0

      gtpu:
        server:
          - dev: eth0

      session:
        - subnet: 10.45.0.0/16
          dnn: internet

      metrics:
        server:
          - dev: eth0
            port: 9090
