apiVersion: apps/v1
kind: Deployment
metadata:
  name: upf
  namespace: open5gs
  labels:
    app: upf

spec:
  replicas: 1

  selector:
    matchLabels:
      app: upf

  template:
    metadata:
      labels:
        app: upf

    spec:
      containers:
      - name: upf
        image: gradiant/open5gs:2.7.0
        imagePullPolicy: IfNotPresent



        command:
        - /bin/bash
        - -c

        args:
        - open5gs-upfd

        securityContext:
          privileged: true

        ports:
        - containerPort: 8805
          protocol: UDP


        volumeMounts:
        - name: tun
          mountPath: /dev/net/tun


      volumes:
      - name: tun
        hostPath:
          path: /dev/net/tun

      - name: upf-config
        configMap:
          name: upf-config


---
apiVersion: v1
kind: Service
metadata:
  name: upf
  namespace: open5gs

spec:
  selector:
    app: upf

  ports:
  - name: pfcp
    protocol: UDP
    port: 8805
    targetPort: 8805

  - name: gtpu
    protocol: UDP
    port: 2152
    targetPort: 2152
