apiVersion: apps/v1
kind: Deployment
metadata:
  name: upf
  namespace: open5gs
  labels:
    app: upf

spec:
  replicas: 1

  selector:
    matchLabels:
      app: upf

  template:
    metadata:
      labels:
        app: upf

    spec:
      containers:
      - name: upf
        image: gradiant/open5gs:2.7.0

        command:
        - /bin/bash
        - -c

        args:
        - open5gs-upfd

        securityContext:
          privileged: true

        ports:
        - containerPort: 8805
          name: pfcp
          protocol: UDP

        - containerPort: 2152
          name: gtpu
          protocol: UDP

        volumeMounts:

        - name: tun
          mountPath: /dev/net/tun

        - name: upf-config
          mountPath: /opt/open5gs/etc/open5gs/upf.yaml
          subPath: upf.yaml


      volumes:

      - name: tun
        hostPath:
          path: /dev/net/tun

      - name: upf-config
        configMap:
          name: upf-config
