apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
      - name: webui
        image: gradiant/open5gs-webui:2.7.0
        ports:
        - containerPort: 3000
        env:
        - name: DB_URI
          value: mongodb://mongodb:27017/open5gs
---
apiVersion: v1
kind: Service
metadata:
  name: webui
  namespace: open5gs
spec:
  type: NodePort
  selector:
    app: webui
  ports:
  - port: 9999
    targetPort: 9999
    nodePort: 30000
