apiVersion: v1
kind: ConfigMap
metadata:
  name: udr-config
  namespace: open5gs

data:
  udr.yaml: |
    db_uri: mongodb://mongodb/open5gs

    logger:
      file: /opt/open5gs/var/log/open5gs/udr.log

    udr:
      sbi:
        server:
        - dev: eth0
          port: 7777

        client:
          nrf:
          - uri: http://nrf:7777
